name: Hoyoverse Code Scraper
on:
    schedule:
        # run daily at 03:00 UTC+8
        - cron: "0 19 * * *"
    workflow_dispatch:

jobs:
    scrape-codes:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12.x
                  cache: "pip"
            - name: install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: run the scraper
              run: |
                  python main.py
            - name: commit and push changes
              run: |
                  git config --local user.name "github-actions[bot]"
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git add .

                  # Check if there are changes
                  if ! git diff-index --quiet HEAD; then
                  git commit -m "update: $(date +'%Y-%m-%d')"
                  git push
                  else
                  echo "No changes to commit"
                  fi
