name: Updating Data
on:
    push:
        branches:
            - main
    schedule:
        # run daily at 03:00 UTC+8
        - cron: "0 19 * * *"
    workflow_dispatch:

jobs:
    updating:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: checkout repo content
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12.x
            - name: install python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: updating data
              run: |
                  python main.py
            - name: finishing up
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "✅ Data updated"
